#!/bin/sh
mount -a
mkdir -p /var/run
cat /etc_ro/motd
nvram_daemon&
goahead&

#for telnet debugging
telnetd

#for syslogd
mkdir -p /var/log
#samba.sh 10.10.10.254/24 ralink rt3052

#the following config for RT3052 FPGA only
#reg s b0110000
#reg w c8 20f02b28
#mii_mgr -s -p 0 -r 4 -v 1061
#mii_mgr -s -p 1 -r 4 -v 1061
#mii_mgr -s -p 2 -r 4 -v 1061
#mii_mgr -s -p 3 -r 4 -v 1061
#mii_mgr -s -p 4 -r 4 -v 1061
#mii_mgr -s -p 0 -r 0 -v b100
#mii_mgr -s -p 1 -r 0 -v b100
#mii_mgr -s -p 2 -r 0 -v b100
#mii_mgr -s -p 3 -r 0 -v b100
#mii_mgr -s -p 4 -r 0 -v b100
#reg w c8 3ff02b28
