# $Id: Makefile,v 1.1.1.1 2010/12/02 04:21:38 walf_wu Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
