# $Id: Makefile,v 1.1.1.1 2010/12/02 04:31:17 walf_wu Exp $

prism54-objs := islpci_eth.o islpci_mgt.o \
                isl_38xx.o isl_ioctl.o islpci_dev.o \
		islpci_hotplug.o oid_mgt.o

obj-$(CONFIG_PRISM54) += prism54.o

